config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]


  get '/login', to: "sessions#login"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def login 
        #login form
        @user = User.new
      
    end 


    def create
        #find our user object 
        @user = User.find_by(email: params[:email])

        #want to check that the user exists
        #then authenticate their password

        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else 
            render :login
        end
        #logging in 
    end 

    def destroy
        session.clear
        redirect_to login_path
        #logging out 
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def new 
        @user = User.new
    end 


    def create 
        @user = User.new(user_params)

        if @user.save
            redirect_to user_path(@user)
        else 
            render :new 
        end 
    end 

    def show 
        @user = User.find(params[:id])
    end 

    def destroy 
        #deleting a user object
    end 

    private 

    def user_params
        params.require(:user).permit(:email, :password)
    end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthWithoutDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= link_to "Log In", login_path %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Logout",  logout_path, method: :delete %>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
Email: <%= f.text_field :email %>
Password: <%= f.text_field :password %>

<%= f.submit "Sign Up" %>
<% end %>